// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RockPaperScissorsWeb {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.RadioButton rockButton;
		
		protected System.Web.UI.WebControls.RadioButton paperButton;
		
		protected System.Web.UI.WebControls.RadioButton scissorsButton;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.WebControls.Label paragraph;
		
		protected System.Web.UI.WebControls.Label computerChoiceLabel;
		
		protected System.Web.UI.WebControls.Label gameOutcome;
	}
}
